const languages = {
    Afrikaans: "🇿🇦",
    Arabic: "🇸🇦",
    Armenian: "🇦🇲",
    Azerbaijani: "🇦🇿",
    Belarusian: "🇧🇾",
    Bosnian: "🇧🇦",
    Bulgarian: "🇧🇬",
    Catalan: "🇪🇸", // No specific flag for Catalan, using Spain's
    Chinese: "🇨🇳",
    Croatian: "🇭🇷",
    Czech: "🇨🇿",
    Danish: "🇩🇰",
    Dutch: "🇳🇱",
    English: "🇬🇧",
    Estonian: "🇪🇪",
    Finnish: "🇫🇮",
    French: "🇫🇷",
    Galician: "🇪🇸", // No specific flag for Galician, using Spain's
    German: "🇩🇪",
    Greek: "🇬🇷",
    Hebrew: "🇮🇱",
    Hindi: "🇮🇳",
    Hungarian: "🇭🇺",
    Icelandic: "🇮🇸",
    Indonesian: "🇮🇩",
    Italian: "🇮🇹",
    Japanese: "🇯🇵",
    Kannada: "🇮🇳", // Using India's flag as there is no specific flag for Kannada
    Kazakh: "🇰🇿",
    Korean: "🇰🇷",
    Latvian: "🇱🇻",
    Lithuanian: "🇱🇹",
    Macedonian: "🇲🇰",
    Malay: "🇲🇾",
    Marathi: "🇮🇳", // Using India's flag as there is no specific flag for Marathi
    Maori: "🇳🇿",
    Nepali: "🇳🇵",
    Norwegian: "🇳🇴",
    Persian: "🇮🇷",
    Polish: "🇵🇱",
    Portuguese: "🇵🇹",
    Romanian: "🇷🇴",
    Russian: "🇷🇺",
    Serbian: "🇷🇸",
    Slovak: "🇸🇰",
    Slovenian: "🇸🇮",
    Spanish: "🇪🇸",
    Swahili: "🇹🇿", // Using Tanzania's flag as Swahili is widely spoken there
    Swedish: "🇸🇪",
    Tagalog: "🇵🇭",
    Tamil: "🇮🇳", // Using India's flag as there is no specific flag for Tamil
    Thai: "🇹🇭",
    Turkish: "🇹🇷",
    Ukrainian: "🇺🇦",
    Urdu: "🇵🇰",
    Vietnamese: "🇻🇳",
    Welsh: "🇬🇧" // Using the UK's flag as there is no specific flag for Welsh
};

export default languages